- name: mysql server confiquer
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.buildin.dnf:
      name: mysql-server
      state: present
  - name: enable and restart mysql
    ansible.buildin.service:
       state: restart
       enable: yes
  - name: set a password
    ansible.buildin.command: mysql_secure_installation --set-root-pass RoboShop@1 

